server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path= /user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /product/api/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Đảm bảo Gateway đăng ký vào Eureka
  instance:
    preferIpAddress: false  # Dùng service name thay vì IP
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}