server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path= /user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /product/**
      default-filters:
        - TokenRelay
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/oms
        registration:
          keycloak:
            provider: keycloak
            client-id: oms_api
            client-secret: Uk5p5zpyPqDkuOhMJAonVNa1KjcE4qjj
            authorization-grant-type: authorization_code



eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}