server:
  port: 8082
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/oms_product?allowPublicKeyRetrieval=true&useSSL=false
    username: duyta
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

duyta:
  upload-file:
    base-uri: file:///F:/Workspace/upload/